---
ELASTIC_TRANSCODER_PIPELINE_ID: transcoding pipeline id
AUTH0_DOMAIN: auth 0 domain
AUTH0_SECRET: Your auth0 client secret
UPLOAD_URI: https://s3.amazonaws.com
ACCESS_KEY: The s3 upload user access key id
SECRET_ACCESS_KEY: The s3 upload user secret access key
SERVICE_ACCOUNT: name of json private key file from firebase
DATABASE_URL: firebase database url
VIDEO_UPLOAD_BUCKET_NAME: your unique upload bucket name
VIDEO_TRANSCODED_BUCKET_NAME: your unique transcoded bucket name